# Generated by Django 5.1.6 on 2025-05-15 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gloss', models.CharField(max_length=255)),
                ('videosrc', models.URLField(max_length=500)),
                ('subset', models.CharField(choices=[('train', 'Training'), ('val', 'Validation'), ('test', 'Testing')], default='train', max_length=5)),
            ],
        ),
    ]
